---
name: FeatureRequest1
description: File a bug report
title: "[Feature]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Ranticha@cmu.ac.th
    validations:
      required: false 

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: request
    attributes:
      label: Type of Request
      description: Select the type of your request
      options:
        - New Feature
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: sugges
    attributes:
      label: What is the OS which you want to suggest?
      multiple: true
      options:
        - Selections
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: detials
    attributes:
      label: What are the details of your suggestions?
      description: Explain what do you want
      render: shell
---